
[project]
name = "coqstoq"
version = "0.1.0"
description = "A benchmark for evaluating automatic proof search tools for Coq."
authors = [{ name = "Kyle Thompson", email = "r7thompson@ucsd.edu" }]
requires-python = ">=3.11, <4.0"

dependencies = [
    "pyyaml >=6.0.2",
    "coqpyt"
]


[project.optional-dependencies]
dev = [
    "black >=24.8.0",
    "ipdb >=0.13.13",
    "ipython >=8.28.0",
    "ipykernel ==6.29.5",
    "pyright >=1.1.400",
]

test = ["pytest >=8.3.3"]


[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "8.3.3"
testpaths = ["tests"]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s %(levelname)s %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"

[tool.pyright]
exclude = ["raw-data", "data", "models", "results"]
extraPaths = ["coqpyt"]

[tool.uv.sources]
coqpyt = { path = "./coqpyt" }
